### ISSUE TITLE
implement request stat tracker middleware

### ISSUE THREAD

**Issue by trevorjpuckett** [precision-sustainable-ag/dst-cover-crop-data-api#36]
**What's wrong**
a mdidleware is needed to track all incoming requests to this api.

**What done looks like**
all incoming requests trigger middleware to send incoming request data to the stats api.

**Where the changes need to be made**
- middleware file should be created
- middleware function should be registered as global middleware
- http request to stats service should occur asynchronously to the reset of the request being handled
- a service file should be created for the StatsService
- a config file should be created for the stats service
- the StatsService file should reference the service & url through the config / env variables ( and any other variables that might be non-static / configurable )

**Comment by dearpriyankasa** [comment]
Related PR - https://github.com/precision-sustainable-ag/dst-cover-crop-data-api/pull/39
